version: '3.9'

services:

  api-your-sport:
    image: api-yoursport:latest
    container_name: api-yoursport
    build:
      context: ../src
      dockerfile: ./YourSport.Api/Dockerfile
    dns:
      - 8.8.8.8
    ports:
      - "5015:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - your-sport
    volumes:
      - ~/.config/:/root/.config
    depends_on:
      - postgres


  postgres:
    image: postgres
    container_name: postgres-your-sport
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: yourSport123456
      POSTGRES_DB: dbYourSport
    ports:
      - "15436:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data 
    networks:
      - your-sport

volumes:
    postgres-volume:
        driver: local

networks: 
  your-sport:
    driver: bridge